"""cambio de nombre de relacion recursiva

Revision ID: d3034a672a61
Revises: 0c214577697c
Create Date: 2025-10-09 22:07:58.915796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3034a672a61'
down_revision: Union[str, Sequence[str], None] = '0c214577697c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instrumento', sa.Column('instrumento_fuente_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_instrumento_padre_id'), 'instrumento', type_='unique')
    op.create_unique_constraint(None, 'instrumento', ['instrumento_fuente_id'])
    op.drop_constraint(op.f('fk_instrumento_padre'), 'instrumento', type_='foreignkey')
    op.create_foreign_key(None, 'instrumento', 'instrumento', ['instrumento_fuente_id'], ['id'])
    op.drop_column('instrumento', 'instrumento_padre_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instrumento', sa.Column('instrumento_padre_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'instrumento', type_='foreignkey')
    op.create_foreign_key(op.f('fk_instrumento_padre'), 'instrumento', 'instrumento', ['instrumento_padre_id'], ['id'])
    op.drop_constraint(None, 'instrumento', type_='unique')
    op.create_unique_constraint(op.f('uq_instrumento_padre_id'), 'instrumento', ['instrumento_padre_id'])
    op.drop_column('instrumento', 'instrumento_fuente_id')
    # ### end Alembic commands ###
