"""Renombra relacion en Instrumento a fuente/derivado

Revision ID: de78e6e570de
Revises: 5be3fc0afa9c
Create Date: 2025-10-09 23:37:36.211132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de78e6e570de'
down_revision: Union[str, Sequence[str], None] = '5be3fc0afa9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instrumento', 'tipo',
               existing_type=sa.TEXT(length=19),
               type_=sa.Enum('ENCUESTA_ESTUDIANTE', 'INFORME_CATEDRA', 'INFORME_SINTETICO', name='tipoinstrumento'),
               existing_nullable=False)
    op.create_unique_constraint(None, 'instrumento', ['instrumento_fuente_id'])
    op.create_foreign_key(None, 'instrumento', 'instrumento', ['instrumento_fuente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instrumento', type_='foreignkey')
    op.drop_constraint(None, 'instrumento', type_='unique')
    op.alter_column('instrumento', 'tipo',
               existing_type=sa.Enum('ENCUESTA_ESTUDIANTE', 'INFORME_CATEDRA', 'INFORME_SINTETICO', name='tipoinstrumento'),
               type_=sa.TEXT(length=19),
               existing_nullable=False)
    # ### end Alembic commands ###
